/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.IOFile;
import controller.TrongException;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DuAn;
import model.NhanVien;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    DefaultTableModel tmDA;
    String fDA;
    List<DuAn> listDA;
    
    DefaultTableModel tmNV;
    String fNV;
    List<NhanVien> listNV;
    
    
    public Main() {
        initComponents();
        
        fDA = "src/main/java/DA.dat";
        String[] da = {"Ma du an", "Ten du an", "Kieu du an", "Tong kinh phi"};
        tmDA  =new DefaultTableModel(da,0);
        jTable2.setModel(tmDA);
        loadDA();
        showDA(listDA);
        
        fNV = "src/main/java/NV.dat";
        String[] nv = {"Ma nhan vien", "Ten nhan vien", "Dia chi", "Chuyen mon"};
        tmNV = new DefaultTableModel(nv,0);
        jTable1.setModel(tmNV);
        loadNV();
        showNV(listNV);
    }
    
    private void loadDA() {
        File f = new File(fDA);
        if (f.exists())
            listDA = IOFile.doc(fDA);
        else
            listDA  = new ArrayList<>();          
    }
    private void showDA(List<DuAn> list) {
        tmDA.setRowCount(0);
        for (DuAn i : list) 
            tmDA.addRow(i.toObjects());
    }
    
    private void loadNV() {
        File f = new File(fNV);
        if (f.exists())
            listNV = IOFile.doc(fNV);
        else
            listNV  = new ArrayList<>();          
    }
    private void showNV(List<NhanVien> list) {
        tmNV.setRowCount(0);
        for (NhanVien i : list) 
            tmNV.addRow(i.toObjects());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        p1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmaNV = new javax.swing.JTextField();
        txttenNV = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtChuyenMon = new javax.swing.JTextField();
        btThemNV = new javax.swing.JButton();
        btLuuNV = new javax.swing.JButton();
        btXoaNV = new javax.swing.JButton();
        btSuaNV = new javax.swing.JButton();
        p2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaDA = new javax.swing.JTextField();
        txtTenDA = new javax.swing.JTextField();
        txtKinhPhi = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btThemDA = new javax.swing.JButton();
        btLuuDA = new javax.swing.JButton();
        btXoaDA = new javax.swing.JButton();
        btsuaDA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("ma nhan vien");

        jLabel2.setText("ten nhan vien");

        jLabel3.setText("dia chi");

        jLabel4.setText("chuyen mon");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmaNV)
                    .addComponent(txttenNV)
                    .addComponent(txtDiaChi)
                    .addComponent(txtChuyenMon, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtChuyenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        btThemNV.setText("Them nhan vien");
        btThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemNVActionPerformed(evt);
            }
        });

        btLuuNV.setText("Luu vao file");
        btLuuNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuNVActionPerformed(evt);
            }
        });

        btXoaNV.setText("Xoa nhan vien");
        btXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaNVActionPerformed(evt);
            }
        });

        btSuaNV.setText("Sua nhan vien");
        btSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btThemNV)
                .addGap(39, 39, 39)
                .addComponent(btSuaNV)
                .addGap(42, 42, 42)
                .addComponent(btXoaNV)
                .addGap(44, 44, 44)
                .addComponent(btLuuNV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThemNV)
                    .addComponent(btLuuNV)
                    .addComponent(btXoaNV)
                    .addComponent(btSuaNV))
                .addGap(0, 129, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thong tin Nhan vien", p1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel5.setText("ma du an");

        jLabel6.setText("ten du an");

        jLabel7.setText("kieu du an");

        jLabel8.setText("tong kinh phi");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nho", "trung binh", "lon" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaDA)
                    .addComponent(txtTenDA)
                    .addComponent(txtKinhPhi, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTenDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtKinhPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        btThemDA.setText("Them Du an");
        btThemDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemDAActionPerformed(evt);
            }
        });

        btLuuDA.setText("Luu vao file");
        btLuuDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuDAActionPerformed(evt);
            }
        });

        btXoaDA.setText("Xoa du an");
        btXoaDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaDAActionPerformed(evt);
            }
        });

        btsuaDA.setText("Sua du an");
        btsuaDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuaDAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btThemDA)
                .addGap(50, 50, 50)
                .addComponent(btXoaDA)
                .addGap(61, 61, 61)
                .addComponent(btsuaDA)
                .addGap(81, 81, 81)
                .addComponent(btLuuDA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThemDA)
                    .addComponent(btLuuDA)
                    .addComponent(btXoaDA)
                    .addComponent(btsuaDA))
                .addGap(0, 129, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thong tin Du an", p2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemNVActionPerformed
        // TODO add your handling code here:
        int  n= listNV.size();
        if (n>0)
            NhanVien.setSma(listNV.get(n-1).getMa()+1);
        txtmaNV.setText(NhanVien.getSma()+"");
        String hoten, diachi, chuyenmon;
        try {
            hoten = txttenNV.getText();
            diachi = txtDiaChi.getText();
            chuyenmon = txtChuyenMon.getText();
            NhanVien nv = new NhanVien(hoten, diachi, chuyenmon);
            tmNV.addRow(nv.toObjects());
            listNV.add(nv);
        } catch (TrongException e) {
            JOptionPane.showMessageDialog(this, "khong de trong");
            return;
        }
                
    }//GEN-LAST:event_btThemNVActionPerformed

    private void btLuuNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuNVActionPerformed
        // TODO add your handling code here:
        IOFile.viet(fNV, listNV);
    }//GEN-LAST:event_btLuuNVActionPerformed

    private void btThemDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemDAActionPerformed
        // TODO add your handling code here:
        int n = listDA.size();
        if (n >0)
            DuAn.setSma(listDA.get(n-1).getMa()+1);
        txtMaDA.setText(DuAn.getSma()+"");
        String ten, kieu;
        double kinhphi;
        try {
            ten = txtTenDA.getText();
            kieu = jComboBox1.getSelectedItem().toString();
            kinhphi = Double.parseDouble(txtKinhPhi.getText());
            DuAn da = new DuAn(ten, kieu, kinhphi);
            tmDA.addRow(da.toObjects());
            listDA.add(da);
        } catch (TrongException e) {
            JOptionPane.showMessageDialog(this, "khong de trong");
            return;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "nhap so");
            return;
        }
    }//GEN-LAST:event_btThemDAActionPerformed

    private void btLuuDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuDAActionPerformed
        // TODO add your handling code here:
        IOFile.viet(fDA, listDA);
    }//GEN-LAST:event_btLuuDAActionPerformed

    private void btXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaNVActionPerformed
        // TODO add your handling code here:
        int r = jTable1.getSelectedRow();
        if (r >=0 || r <jTable1.getRowCount()){
            tmNV.removeRow(r);
            listNV.remove(r);
        }
        else {
            JOptionPane.showMessageDialog(this, "chon dich vu de xoa");
            return;
        }
    }//GEN-LAST:event_btXoaNVActionPerformed

    private void btXoaDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaDAActionPerformed
        // TODO add your handling code here:
        int r = jTable2.getSelectedRow();
        if (r >=00 && r <jTable2.getRowCount()){
            tmDA.removeRow(r);
            listDA.remove(r);
        }
        else {
            JOptionPane.showMessageDialog(this, "chon dich vu de xoa");
            return;
        }
            
    }//GEN-LAST:event_btXoaDAActionPerformed

    private void btSuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaNVActionPerformed
        // TODO add your handling code here:
        int r= jTable1.getSelectedRow();
        if (r >=0 && r <jTable1.getRowCount()){
            String hoten = txttenNV.getText();
            String diachi = txtDiaChi.getText();
            String chuyenmon = txtChuyenMon.getText();
            tmNV.setValueAt(hoten, r, 1);
            tmNV.setValueAt(diachi, r, 2);
            tmNV.setValueAt(chuyenmon, r, 3);
            int ma = Integer.parseInt(txtmaNV.getText());
            NhanVien nv = new NhanVien(ma, hoten, diachi, chuyenmon);
            listNV.set(r, nv);
            
        } else {
            JOptionPane.showMessageDialog(this, "Chon dich vu de sua");
            return;
        }

    }//GEN-LAST:event_btSuaNVActionPerformed

    private void btsuaDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuaDAActionPerformed
        // TODO add your handling code here:
        int r = jTable2.getSelectedRow();
        if ( r >=0 && r <jTable2.getRowCount()) {
            String ten = txtTenDA.getText();
            String kieu = jComboBox1.getSelectedItem().toString();
            double kinhphi = Double.parseDouble(txtKinhPhi.getText());
            tmDA.setValueAt(ten, r, 1);
            tmDA.setValueAt(kieu, r, 2);
            tmDA.setValueAt(kinhphi, r, 3);
            int ma =Integer.parseInt(txtMaDA.getText());
            DuAn da = new DuAn(ma, ten, kieu, kinhphi);
            listDA.set(r, da);
        }  else {
            JOptionPane.showMessageDialog(this, "Chon dich vu de sua");
            return;
        }

    }//GEN-LAST:event_btsuaDAActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int r = jTable2.getSelectedRow();
        txtMaDA.setText(tmDA.getValueAt(r, 0).toString());
        txtTenDA.setText(tmDA.getValueAt(r, 1).toString());
        jComboBox1.setSelectedItem(tmDA.getValueAt(r, 2).toString());
        txtKinhPhi.setText(tmDA.getValueAt(r, 3).toString());
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int r= jTable1.getSelectedRow();
        txtmaNV.setText(tmNV.getValueAt(r, 0).toString());
        txttenNV.setText(tmNV.getValueAt(r, 1).toString());
        txtDiaChi.setText(tmNV.getValueAt(r, 2).toString());
        txtChuyenMon.setText(tmNV.getValueAt(r, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLuuDA;
    private javax.swing.JButton btLuuNV;
    private javax.swing.JButton btSuaNV;
    private javax.swing.JButton btThemDA;
    private javax.swing.JButton btThemNV;
    private javax.swing.JButton btXoaDA;
    private javax.swing.JButton btXoaNV;
    private javax.swing.JButton btsuaDA;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JTextField txtChuyenMon;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtKinhPhi;
    private javax.swing.JTextField txtMaDA;
    private javax.swing.JTextField txtTenDA;
    private javax.swing.JTextField txtmaNV;
    private javax.swing.JTextField txttenNV;
    // End of variables declaration//GEN-END:variables
}
