/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.IOFile;
import controller.TrongExcception;
import java.io.File;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MonHoc;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    DefaultTableModel tmMH;
    String fMH;
    List<MonHoc> listMH;
    
    public Main() {
        initComponents();
        fMH = "src/main/java/controller/MH.dat";
        String[] mh = {"Ma mon hoc", "Ten mon hoc", "Tong so tiet", "Tong ly thuyet", "Kinh phi"};
        tmMH = new DefaultTableModel(mh, 0);
        jTable1.setModel(tmMH);
        loadMH();
        showMH(listMH);
    }
    private void loadMH() {
        File f = new File(fMH);
        if (f.exists())
            listMH = IOFile.doc(fMH);
        else 
            listMH = new ArrayList<>();
    }
    private void showMH(List<MonHoc> list) {
        tmMH.setRowCount(0);
        for (MonHoc i :list) 
            tmMH.addRow(i.toObjects());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmaMH = new javax.swing.JTextField();
        txttenMH = new javax.swing.JTextField();
        txttong = new javax.swing.JTextField();
        txtLT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTimMH = new javax.swing.JTextField();
        btThemMH = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btLUU = new javax.swing.JButton();
        btTim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ma mon hoc");

        jLabel2.setText("Ten mon hoc");

        jLabel3.setText("Tong so tiet");

        jLabel4.setText("Tong ly thuyet");

        txtmaMH.setEditable(false);

        jLabel6.setText("Nhap thong tin tim");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtmaMH)
                    .addComponent(txttenMH)
                    .addComponent(txttong)
                    .addComponent(txtLT)
                    .addComponent(txtTimMH, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttenMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTimMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btThemMH.setText("Them");
        btThemMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemMHActionPerformed(evt);
            }
        });

        btSua.setText("Sua");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setText("Xoa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btLUU.setText("Luu");
        btLUU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLUUActionPerformed(evt);
            }
        });

        btTim.setText("Tim");
        btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btThemMH)
                    .addComponent(btSua)
                    .addComponent(btXoa)
                    .addComponent(btLUU)
                    .addComponent(btTim))
                .addGap(0, 151, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btThemMH)
                        .addGap(41, 41, 41)
                        .addComponent(btSua)
                        .addGap(47, 47, 47)
                        .addComponent(btXoa)
                        .addGap(33, 33, 33)
                        .addComponent(btLUU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btTim)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thong tin Mon hoc", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThemMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemMHActionPerformed
        // TODO add your handling code here:
        int n = listMH.size();
        if (n >0) 
            MonHoc.setSma(listMH.get(n-1).getMa()+1);
        txtmaMH.setText(MonHoc.getSma()+"");
        String ten;
        int tong, tongLT;
        double kinhphi;
        try {
            ten = txttenMH.getText();
            tong = Integer.parseInt(txttong.getText());
            tongLT = Integer.parseInt(txtLT.getText());
            kinhphi = tongLT*27500+(tong-tongLT)*7*275;
            MonHoc mh = new MonHoc(ten, tong, tongLT, kinhphi);
            tmMH.addRow(mh.toObjects());
            listMH.add(mh);
        } catch (TrongExcception e) {
            JOptionPane.showMessageDialog(this, "khong de trong");
            return;
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "nhap so!");
            return;
        }
    }//GEN-LAST:event_btThemMHActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int r = jTable1.getSelectedRow();
        if (r >=0 && r <jTable1.getRowCount()) {
            String ten = txttenMH.getText();
            int tong = Integer.parseInt(txttong.getText());
            int tongLT = Integer.parseInt(txtLT.getText());
            int ma = Integer.parseInt(txtmaMH.getText());
            double kinhphi = tongLT*2750+(tong-tongLT)*7*275;
            tmMH.setValueAt(tong, r, 2);
            tmMH.setValueAt(tongLT, r, 3);
            tmMH.setValueAt(ten, r, 1);
            tmMH.setValueAt(kinhphi, r, 4);
            MonHoc mh = new MonHoc(ma, ten, tong, tongLT, kinhphi);
            listMH.set(r, mh);   
        } else {
            JOptionPane.showMessageDialog(this, "Chon mon hoc de sua");
            return;
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int r = jTable1.getSelectedRow();
        txtmaMH.setText(tmMH.getValueAt(r, 0).toString());
        txttenMH.setText(tmMH.getValueAt(r, 1).toString());
        txttong.setText(tmMH.getValueAt(r, 2).toString());
        txtLT.setText(tmMH.getValueAt(r, 3).toString());      
    }//GEN-LAST:event_jTable1MouseClicked

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        int r = jTable1.getSelectedRow();
        if (r >=0 && r <jTable1.getRowCount()) {
            tmMH.removeRow(r);
            listMH.remove(r);
        }
        else {
            JOptionPane.showMessageDialog(this, "Chon mon hoc de xoa");
            return;
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btLUUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLUUActionPerformed
        // TODO add your handling code here:
        IOFile.viet(fMH, listMH);
    }//GEN-LAST:event_btLUUActionPerformed

    private void btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimActionPerformed
        // TODO add your handling code here:
        String key = txtTimMH.getText().trim().toLowerCase();
        List<MonHoc> list = new ArrayList<>();
        for (MonHoc i : listMH) {
            if (i.getTen().toLowerCase().contains(key)) {
                list.add(i);
            }
        }
        showMH(list);
    }//GEN-LAST:event_btTimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLUU;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThemMH;
    private javax.swing.JButton btTim;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtLT;
    private javax.swing.JTextField txtTimMH;
    private javax.swing.JTextField txtmaMH;
    private javax.swing.JTextField txttenMH;
    private javax.swing.JTextField txttong;
    // End of variables declaration//GEN-END:variables
}
